# ===============================
# APPLICATION
# ===============================
spring.application.name=AuthService
server.port=8081
frontend.url=http://localhost:5173

spring.profiles.active=local

spring.security.filter.dispatcher-types=request,async

# ===============================
# MYSQL DATABASE CONFIGURATION
# ===============================


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/collabspace_db?allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
logging.level.org.springframework.security=INFO

# ===============================
# MAIL CONFIGURATION
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pranalipathare71@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# GROQ AI CONFIGURATION
# ===============================
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.key=${GROQ_API_KEY}

# ===============================
# OAUTH2
# ===============================

# GitHub OAuth2
spring.security.oauth2.client.registration.github.client-id=Ov23liGRqSER62QY9idm
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=973772421733-2b7l9kr0fn8p6hchtil9lrna2vd6e90q.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# ===============================
# JAAS CONFIGURATION
# ===============================
jaas.app.id=${JAAS_APP_ID}
jaas.api.key.id=${JAAS_API_KEY_ID}
jaas.private.key.path=classpath:jaas-private-key.pem